// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyvoakkcbzpcfolrwqht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5dm9ha2tjYnpwY2ZvbHJ3cWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTI3NjUsImV4cCI6MjA2MDU2ODc2NX0.d0quTQ_24HFDM9-sgKTVhwfFBJiujYsuvvEpeFJBd1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);